// Auto-generated by wasmify gen-proto. DO NOT EDIT.
#include <cstdlib>
#include <cstring>
#include <cstdint>
#include <string>
#include <vector>

#include "tools/wasm/vipswasm.h"

#define WASM_EXPORT(name) __attribute__((export_name(#name)))
#define WASM_IMPORT(module, name) __attribute__((import_module(#module), import_name(#name)))

extern "C" {

WASM_EXPORT(wasm_alloc)
void* wasm_alloc(int32_t size) { return malloc(size); }

WASM_EXPORT(wasm_free)
void wasm_free(void* ptr) { free(ptr); }

WASM_IMPORT(wasmify, callback_invoke)
int64_t wasmify_callback_invoke(int32_t callback_id, int32_t method_id, void* req, int32_t req_len);

// ======================================
// Proto3 wire format helpers
// ======================================

static int64_t encode_result(void* ptr, int32_t len) {
    return (static_cast<int64_t>(reinterpret_cast<uintptr_t>(ptr)) << 32) | static_cast<uint32_t>(len);
}

class ProtoReader {
public:
    const uint8_t* pos_;
    const uint8_t* end_;
    uint32_t last_field_;
    uint32_t last_wire_;

    ProtoReader(const void* data, int32_t len)
        : pos_(static_cast<const uint8_t*>(data)),
          end_(pos_ + len), last_field_(0), last_wire_(0) {}

    bool has_data() const { return pos_ < end_; }

    bool next() {
        if (pos_ >= end_) return false;
        uint64_t tag;
        if (!read_varint_raw(&tag)) return false;
        last_field_ = static_cast<uint32_t>(tag >> 3);
        last_wire_ = static_cast<uint32_t>(tag & 7);
        return true;
    }

    uint32_t field() const { return last_field_; }
    uint32_t wire() const { return last_wire_; }

    uint64_t read_varint() {
        uint64_t v = 0;
        read_varint_raw(&v);
        return v;
    }

    int32_t read_int32() { return static_cast<int32_t>(read_varint()); }
    int64_t read_int64() { return static_cast<int64_t>(read_varint()); }
    uint32_t read_uint32() { return static_cast<uint32_t>(read_varint()); }
    uint64_t read_uint64() { return read_varint(); }
    bool read_bool() { return read_varint() != 0; }

    float read_float() {
        float v = 0;
        if (pos_ + 4 <= end_) { memcpy(&v, pos_, 4); pos_ += 4; }
        return v;
    }

    double read_double() {
        double v = 0;
        if (pos_ + 8 <= end_) { memcpy(&v, pos_, 8); pos_ += 8; }
        return v;
    }

    std::string read_string() {
        uint64_t len = read_varint();
        if (pos_ + len > end_) { pos_ = end_; return ""; }
        std::string s(reinterpret_cast<const char*>(pos_), static_cast<size_t>(len));
        pos_ += len;
        return s;
    }

    // Returns a sub-reader for an embedded message
    ProtoReader read_submessage() {
        uint64_t len = read_varint();
        if (pos_ + len > end_) { pos_ = end_; return ProtoReader(nullptr, 0); }
        ProtoReader sub(pos_, static_cast<int32_t>(len));
        pos_ += len;
        return sub;
    }

    void skip() {
        switch (last_wire_) {
        case 0: read_varint(); break;
        case 1: pos_ += 8; break;
        case 2: { uint64_t len = read_varint(); pos_ += len; } break;
        case 5: pos_ += 4; break;
        default: pos_ = end_; break;
        }
        if (pos_ > end_) pos_ = end_;
    }

private:
    bool read_varint_raw(uint64_t* val) {
        *val = 0;
        for (int shift = 0; shift < 64 && pos_ < end_; shift += 7) {
            uint8_t byte = *pos_++;
            *val |= static_cast<uint64_t>(byte & 0x7F) << shift;
            if ((byte & 0x80) == 0) return true;
        }
        return false;
    }
};

// ProtoWriter defers its initial heap allocation until the first write.
// Serialising an empty response therefore costs zero malloc/free pairs;
// the previous eager allocation leaked a 128-byte buffer on every call
// that returned no bytes (setters, voids, empty getters), which for a
// single-run parse/analyze loop piled up millions of bytes of wasm heap
// until the module ran out of memory.
class ProtoWriter {
public:
    uint8_t* data_;
    int32_t size_;
    int32_t cap_;

    ProtoWriter() : data_(nullptr), size_(0), cap_(0) {}

    // Destructor frees any heap buffer the writer still owns. Two
    // usage shapes own data_ differently. (1) The wasm export
    // return path ends with finish(); finish() transfers ownership
    // of data_ to the host (host calls wasm_free after reading) and
    // NULLs data_ here so this destructor skips the free. (2) The
    // callback trampoline (C++ to Go) hands data_/size_ to
    // wasmify_callback_invoke; the host READS but does not take
    // ownership, so when the writer goes out of scope this
    // destructor must release data_. Without (2), every callback
    // dispatch leaks 128+ bytes of wasm heap; after enough rounds
    // dlmalloc fragments and subsequent allocations either return
    // NULL or trip OOB inside the allocator's freelist walk.
    ~ProtoWriter() {
        if (data_ != nullptr) {
            free(data_);
            data_ = nullptr;
        }
    }

    // Disable copy: data_ is malloc'd; copying would alias the
    // pointer and double-free at scope exit.
    ProtoWriter(const ProtoWriter&) = delete;
    ProtoWriter& operator=(const ProtoWriter&) = delete;

    void ensure(int32_t need) {
        if (data_ == nullptr) {
            cap_ = need > 128 ? need : 128;
            data_ = static_cast<uint8_t*>(malloc(cap_));
            return;
        }
        while (size_ + need > cap_) {
            cap_ *= 2;
            data_ = static_cast<uint8_t*>(realloc(data_, cap_));
        }
    }

    void write_raw(const void* src, int32_t len) {
        ensure(len);
        memcpy(data_ + size_, src, len);
        size_ += len;
    }

    void write_varint(uint64_t val) {
        ensure(10);
        while (val > 0x7F) {
            data_[size_++] = static_cast<uint8_t>((val & 0x7F) | 0x80);
            val >>= 7;
        }
        data_[size_++] = static_cast<uint8_t>(val);
    }

    void write_tag(uint32_t field, uint32_t wire) {
        write_varint((static_cast<uint64_t>(field) << 3) | wire);
    }

    void write_int32(uint32_t field, int32_t val) {
        if (val == 0) return;
        write_tag(field, 0);
        write_varint(static_cast<uint64_t>(static_cast<uint32_t>(val)));
    }

    void write_int64(uint32_t field, int64_t val) {
        if (val == 0) return;
        write_tag(field, 0);
        write_varint(static_cast<uint64_t>(val));
    }

    void write_uint32(uint32_t field, uint32_t val) {
        if (val == 0) return;
        write_tag(field, 0);
        write_varint(val);
    }

    void write_uint64(uint32_t field, uint64_t val) {
        if (val == 0) return;
        write_tag(field, 0);
        write_varint(val);
    }

    void write_bool(uint32_t field, bool val) {
        if (!val) return;
        write_tag(field, 0);
        write_varint(1);
    }

    void write_float(uint32_t field, float val) {
        uint32_t bits;
        memcpy(&bits, &val, 4);
        if (bits == 0) return;
        write_tag(field, 5);
        write_raw(&val, 4);
    }

    void write_double(uint32_t field, double val) {
        uint64_t bits;
        memcpy(&bits, &val, 8);
        if (bits == 0) return;
        write_tag(field, 1);
        write_raw(&val, 8);
    }

    void write_string(uint32_t field, const std::string& s) {
        if (s.empty()) return;
        write_tag(field, 2);
        write_varint(s.size());
        write_raw(s.data(), static_cast<int32_t>(s.size()));
    }

    void write_string(uint32_t field, const char* s, uint32_t len) {
        if (len == 0) return;
        write_tag(field, 2);
        write_varint(len);
        write_raw(s, len);
    }

    void write_submessage(uint32_t field, const ProtoWriter& sub) {
        if (sub.size_ == 0) return;
        write_tag(field, 2);
        write_varint(sub.size_);
        write_raw(sub.data_, sub.size_);
    }

    void write_handle(uint32_t field, uint64_t ptr) {
        if (ptr == 0) return;
        // Handle is a submessage with field 1 = uint64 ptr
        ProtoWriter sub;
        sub.write_uint64(1, ptr);
        write_submessage(field, sub);
        free(sub.data_);
    }

    // ---- Repeated primitive helpers (packed encoding) ----
    // Note: this class lives inside extern "C" {}, so we cannot declare
    // member templates. Each packed variant is written out explicitly.

    void write_repeated_int32(uint32_t field, const std::vector<int32_t>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (int32_t v : vec) sub.write_varint(static_cast<uint64_t>(static_cast<uint32_t>(v)));
        write_submessage(field, sub);
        free(sub.data_);
    }
    void write_repeated_int64(uint32_t field, const std::vector<int64_t>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (int64_t v : vec) sub.write_varint(static_cast<uint64_t>(v));
        write_submessage(field, sub);
        free(sub.data_);
    }
    void write_repeated_uint32(uint32_t field, const std::vector<uint32_t>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (uint32_t v : vec) sub.write_varint(static_cast<uint64_t>(v));
        write_submessage(field, sub);
        free(sub.data_);
    }
    void write_repeated_uint64(uint32_t field, const std::vector<uint64_t>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (uint64_t v : vec) sub.write_varint(v);
        write_submessage(field, sub);
        free(sub.data_);
    }
    void write_repeated_bool(uint32_t field, const std::vector<bool>& vec) {
        if (vec.empty()) return;
        ProtoWriter sub;
        for (bool v : vec) sub.write_varint(v ? 1u : 0u);
        write_submessage(field, sub);
        free(sub.data_);
    }

    void write_repeated_double(uint32_t field, const std::vector<double>& vec) {
        if (vec.empty()) return;
        write_tag(field, 2);
        write_varint(static_cast<uint64_t>(vec.size()) * 8u);
        for (double v : vec) write_raw(&v, 8);
    }
    void write_repeated_float(uint32_t field, const std::vector<float>& vec) {
        if (vec.empty()) return;
        write_tag(field, 2);
        write_varint(static_cast<uint64_t>(vec.size()) * 4u);
        for (float v : vec) write_raw(&v, 4);
    }

    // Repeated string/bytes are NOT packed in proto3; each element emits
    // its own length-delimited tag.
    void write_repeated_string(uint32_t field, const std::vector<std::string>& vec) {
        for (const auto& s : vec) {
            write_tag(field, 2);
            write_varint(s.size());
            write_raw(s.data(), static_cast<int32_t>(s.size()));
        }
    }

    // Repeated handle: each element becomes a length-delimited submessage
    // with field 1 = uint64 ptr. Null pointers are skipped. Two overloads
    // cover the common vector<T*> and vector<const T*> cases; note that we
    // cannot use a member template here (extern "C" block).
    void write_repeated_handle(uint32_t field, const std::vector<void*>& vec) {
        for (void* p : vec) {
            if (p == nullptr) continue;
            write_handle(field, reinterpret_cast<uint64_t>(p));
        }
    }

    void write_error(const char* msg) {
        write_string(15, msg, static_cast<uint32_t>(strlen(msg)));
    }

    void write_error(const std::string& msg) {
        write_string(15, msg);
    }

    int64_t finish() {
        // Empty response: the host short-circuits on length and never
        // calls wasm_free, so any lazy-allocated buffer would leak.
        // Free it here and return nullptr so the host skips cleanly.
        if (size_ == 0) {
            if (data_ != nullptr) {
                free(data_);
                data_ = nullptr;
                cap_ = 0;
            }
            return encode_result(nullptr, 0);
        }
        // Transfer ownership of data_ to the host. Clear our pointer
        // so the destructor does not double-free what the host now
        // owns and will release via wasm_free after reading.
        uint8_t* released = data_;
        int32_t released_size = size_;
        data_ = nullptr;
        size_ = 0;
        cap_ = 0;
        return encode_result(released, released_size);
    }
};

// Read handle ptr from a submessage (field 1 = uint64)
static uint64_t read_handle_ptr(ProtoReader& reader) {
    ProtoReader sub = reader.read_submessage();
    uint64_t ptr = 0;
    while (sub.has_data() && sub.next()) {
        if (sub.field() == 1) ptr = sub.read_uint64();
        else sub.skip();
    }
    return ptr;
}

// Read handle ptr from top-level message (field 1 = uint64)
static uint64_t read_handle_direct(const void* req, int32_t req_len) {
    ProtoReader reader(req, req_len);
    uint64_t ptr = 0;
    while (reader.has_data() && reader.next()) {
        if (reader.field() == 1) ptr = reader.read_uint64();
        else reader.skip();
    }
    return ptr;
}

// ======================================
// Service and method IDs
// ======================================

static const int32_t SERVICE_VIPSWASM = 0;
static const int32_t METHOD_VIPSWASM_EXTRACT_AREA = 0;
static const int32_t METHOD_VIPSWASM_RESIZE_NEAREST = 1;
static const int32_t METHOD_VIPSWASM_VERSION = 2;

// Service 0: vipswasm (free functions)
WASM_EXPORT(w_0_0)
int64_t w_0_0(void* req, int32_t req_len) { // extract_area
    std::string src{};
    uint32_t src_width{};
    uint32_t src_height{};
    uint32_t left{};
    uint32_t top{};
    uint32_t width{};
    uint32_t height{};
    ProtoReader reader(req, req_len);
    while (reader.has_data() && reader.next()) {
        switch (reader.field()) {
        case 1: src = reader.read_string(); break;
        case 2: src_width = reader.read_uint32(); break;
        case 3: src_height = reader.read_uint32(); break;
        case 4: left = reader.read_uint32(); break;
        case 5: top = reader.read_uint32(); break;
        case 6: width = reader.read_uint32(); break;
        case 7: height = reader.read_uint32(); break;
        default: reader.skip(); break;
        }
    }
    auto _result = vipswasm::extract_area(src, src_width, src_height, left, top, width, height);
    ProtoWriter _pw;
    _pw.write_string(1, std::string(_result));
    return _pw.finish();
}

WASM_EXPORT(w_0_1)
int64_t w_0_1(void* req, int32_t req_len) { // resize_nearest
    std::string src{};
    uint32_t src_width{};
    uint32_t src_height{};
    uint32_t dst_width{};
    uint32_t dst_height{};
    ProtoReader reader(req, req_len);
    while (reader.has_data() && reader.next()) {
        switch (reader.field()) {
        case 1: src = reader.read_string(); break;
        case 2: src_width = reader.read_uint32(); break;
        case 3: src_height = reader.read_uint32(); break;
        case 4: dst_width = reader.read_uint32(); break;
        case 5: dst_height = reader.read_uint32(); break;
        default: reader.skip(); break;
        }
    }
    auto _result = vipswasm::resize_nearest(src, src_width, src_height, dst_width, dst_height);
    ProtoWriter _pw;
    _pw.write_string(1, std::string(_result));
    return _pw.finish();
}

WASM_EXPORT(w_0_2)
int64_t w_0_2(void* req, int32_t req_len) { // version
    ProtoReader reader(req, req_len);
    while (reader.has_data() && reader.next()) {
        switch (reader.field()) {
        default: reader.skip(); break;
        }
    }
    uint32_t _result = vipswasm::version();
    ProtoWriter _pw;
    _pw.write_uint32(1, _result);
    return _pw.finish();
}

// ======================================
// Runtime helpers
// ======================================

#include <typeinfo>
#include <cxxabi.h>

WASM_EXPORT(wasmify_get_type_name)
int64_t wasmify_get_type_name(void* req, int32_t req_len) {
    ProtoReader reader(req, req_len);
    uint64_t ptr = 0;
    while (reader.has_data() && reader.next()) {
        if (reader.field() == 1) ptr = reader.read_uint64();
        else reader.skip();
    }
    if (ptr == 0) { ProtoWriter pw; pw.write_error("null handle"); return pw.finish(); }
    ProtoWriter pw;
    pw.write_error("unknown type");
    return pw.finish();
}

WASM_EXPORT(wasm_init)
int32_t wasm_init() { return 0; }

WASM_EXPORT(wasm_shutdown)
void wasm_shutdown() { }

} // extern "C"
