// Auto-generated by wasmify gen-proto. DO NOT EDIT.
#ifndef VIPSWASM_API_BRIDGE_H_
#define VIPSWASM_API_BRIDGE_H_

#include <cstdint>

extern "C" {

void* wasm_alloc(int32_t size);
void wasm_free(void* ptr);
int32_t wasm_init();
void wasm_shutdown();

// Per-method entry points are exported as `w_<svc>_<mid>` and
// `wasmify_get_type_name`; callers look them up by name via
// `mod.ExportedFunction(...)` rather than going through a
// single dispatch wrapper.

} // extern "C"

#endif // VIPSWASM_API_BRIDGE_H_
